### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by Jordan-T** [johnmeunier/vuenote#2]
Est il possible de revoir l'indentation des fichiers `.vue` pour être homogène avec les fichiers `.js` (2 espaces)

**Comment by johnmeunier** [comment]
Yes, faudrait faire un fichier de conf pour VSCode

**Comment by Jordan-T** [comment]
@johnmeunier Pourtant l'indentation est configuré en 2 spaces dans l'editor config ...
